# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import TimeServer_pb2 as TimeServer__pb2


class CalculateTimeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Registry = channel.unary_unary(
                '/com.WaitingTimeServer.grpc.CalculateTime/Registry',
                request_serializer=TimeServer__pb2.EstimatedTimeRequest.SerializeToString,
                response_deserializer=TimeServer__pb2.TimeResponse.FromString,
                )


class CalculateTimeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Registry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculateTimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Registry': grpc.unary_unary_rpc_method_handler(
                    servicer.Registry,
                    request_deserializer=TimeServer__pb2.EstimatedTimeRequest.FromString,
                    response_serializer=TimeServer__pb2.TimeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.WaitingTimeServer.grpc.CalculateTime', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CalculateTime(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Registry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/com.WaitingTimeServer.grpc.CalculateTime/Registry',
            TimeServer__pb2.EstimatedTimeRequest.SerializeToString,
            TimeServer__pb2.TimeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
